services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      ENV: development
      DATABASE_URL: postgresql://kalah_user:kalah_password@db:5432/kalah_db
    depends_on:
      - db
    networks:
      - kalah_network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      ENV: development
    networks:
      - kalah_network

  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kalah_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: kalah_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kalah_network

volumes:
  postgres_data:

networks:
  kalah_network:
    driver: bridge
